derivatives:
  - name: raw-hemianotacs
    path: /Volumes/levy/raw/valerocabre/hemianotACS/Data/derivatives/bids
    bids: yes
    check-type: raw-qc # group an array of metrics
    datatype:
      differentiate-constructors: yes
      differentiate-chnumber: ...
    

  - name: mbp-hemianotacs
    path: /Volumes/levy/raw/valerocabre/hemianotACS/Data/derivatives/eeg/mne-bids-pipeline
    bids: yes
    check-type: raw-qc

  - name: RSeeg-hemianotacs
    path: /Volumes/levy/raw/valerocabre/hemianotACS/Data/derivatives/eeg/rs-eeg
    bids: no
    check-type: raw-qc

  - name: raw-clonesatacs
    path: /Volumes/levy/raw/valerocabre/clonesa/Data/clonesatACS/derivatives/bids
    bids: yes
    check-type: raw-qc

  - name: mbp-clonesatacs
    path: /Volumes/levy/raw/valerocabre/clonesa/Data/clonesatACS/derivatives/mne-bids-pipeline
    bids: yes
    check-type: raw-qc

  - name: RSeeg-clonesatacs
    path: /Volumes/levy/raw/valerocabre/clonesa/Data/clonesatACS/derivatives/rs-eeg
    bids: no
    check-type: raw-qc